[settings]
paranoid = true
disable_tools = ['packer']
legacy_version_file = false
fetch_remote_versions_timeout = '10'
experimental = true


[settings.npm]
bun = true

[tools]
awscli = "latest"
bun = "latest"
checkov = "latest"
dynatrace-monaco = "latest"
gcloud = "latest"
k9s = "latest"
krew = "latest"
kubectl = "1.31.12"
kubectx = "latest"
sops = "latest"
terraform = "latest"
tf-summarize = "latest"
