[settings]
paranoid = true
disable_tools = ['packer']
legacy_version_file = false
fetch_remote_versions_timeout = '10'


[settings.npm]
bun = true

[tools]
awscli = "latest"
bun = "latest"
checkov = "latest"
dynatrace-monaco = "latest"
k9s = "latest"
krew = "latest"
kubectl = "1.30.11"
kubectx = "latest"
sops = "latest"
terraform = "1.12.2"
tf-summarize = "latest"
